[general]
host = "::"
port = 80
root = "/www"
log-level = "info"
cache-control-headers = true
compression = true
threads-multiplier = 4
grace-period = 5
log-remote-address = true
compression-static = true
health = false

[advanced]
[[advanced.rewrites]]
source = "/{about,login,terms,contact,privacy,register}"
destination = "/"
